### ISSUE TITLE
Can you provide detailed Docker run command?

### ISSUE THREAD

**Issue by huweiunique** [Dadoum/anisette-v3-server#1]
hello,
What is the Docker run command for this repository, and can it be updated in the ReadMe.md file? I would like to deploy it myself, but I couldn't find any instructions on Docker Hub. I only found the image 'dadoum/anisette-v3-server:latest'.
 thanks!

**Comment by Macleykun** [comment]
Can ya try this for me?
docker run -d --restart always --name anisette-v3 -p 6969:6969 --volume anisette-v3_data:/home/Alcoholic/.config/anisette-v3/lib/ ghcr.io/dadoum/anisette-v3-server:latest
