### ISSUE TITLE
Showing as outdated and no files showing within local directory

### ISSUE THREAD

**Issue by aptonline** [Dadoum/anisette-v3-server#12]
Installed successfully on Synology and log looks clean.

![image](https://github.com/Dadoum/anisette-v3-server/assets/190136/4ac78a07-5eed-4b3b-8506-f874aa2a68fa)

But no supporting files are being saved to the local directory and when I connect to the server I'm getting an outdated anisette-server warning:

![IMG_5300](https://github.com/Dadoum/anisette-v3-server/assets/190136/c5e8da04-a14b-4ae5-b26e-c9035c665b42)

Any ideas?

**Comment by Dadoum** [comment]
Are you sure you typed the URL correctly with the right port?

**Comment by aptonline** [comment]
Yes, correct port and its open.  (testing locally)

![IMG_5303](https://github.com/Dadoum/anisette-v3-server/assets/190136/3f0c335f-30a0-4976-b051-1ea7783deec4)

Should I be seeing the libraries downloaded from the servers in the directory I mapped? is this the issue?

**Comment by Dadoum** [comment]
Where did you get that executable??

**Comment by Dadoum** [comment]
anisette-server is the outdated server, anisette-v3-server is the new one

**Comment by aptonline** [comment]
Really not sure why I missed that, that was the issue, thanks for the help.

Interesting I can't seem to map the volume to a local directory without getting permissions errors, Tried setting GID/UID and still a problem so ended up relying on `anisette-v3_data`.

**Comment by aptonline** [comment]
Closing as resolved.
