### ISSUE TITLE
SIGSEGV error on the pi5

### ISSUE THREAD

**Issue by gilcu3** [Dadoum/anisette-v3-server#18]
I compiled on the raspberry pi 5 (aarch64). Compilation worked correctly. After launching, it downloads libraries (writes Done!), and then fails with SIGSEGV. Doing the same steps in a linux laptop works without issues. Do you know if that can be fixed? I can grab logs if needed.

**Comment by Dadoum** [comment]
It should be fixable. Have you built it yourself? Maybe you can change one line in dub.selections.json

```patch
+ "provision": {"version":"05277953592347c9c0de8d491db50eee29443902","repository":"git+https://github.com/Dadoum/Provision.git"},
- "provision": {"version":"fa028b6f4e6e2704bf43f92031fe5c3223045f64","repository":"git+https://github.com/Dadoum/Provision.git"},
```

that will probably make anisette-v3-server leak some memory, but it should work

**Comment by gilcu3** [comment]
I built myself. Making that change led to another error:
`ssl_adapter.d(204): loading openssl: unknown version Tuple!(int, "major", int, "minor")(3, 2) for init`
I guess downgrading Provision makes my openssl version too new :(

**Comment by Dadoum** [comment]
That one too

```patch
+ "requests": "2.1.2",
- "requests": "2.1.1",
```

**Comment by gilcu3** [comment]
Wonderful, now it is working :) Thank you very much
