### ISSUE TITLE
Can not run as Render web service

### ISSUE THREAD

**Issue by shalom-aviv** [Dadoum/anisette-v3-server#4]
Hi 

At first Is it possible at all to run this repo as Render web service?

If Yes could you please assist?
How can I fix it?
<img width="1427" alt="Screenshot 2023-10-13 at 3 57 20 AM" src="https://github.com/Dadoum/anisette-v3-server/assets/78256107/e4088353-133c-4470-ba13-8020d2a5336e">

Thank you!

**Comment by Dadoum** [comment]
@shalom-aviv is it working now?

**Comment by shalom-aviv** [comment]
Now All is OK

<img width="1002" alt="Screenshot 2023-10-14 at 12 50 08 PM" src="https://github.com/Dadoum/anisette-v3-server/assets/78256107/943e2a47-e4f9-4da5-9ce0-152b78bbcc93">
